project_name : "foundational_agents"
experiment_name : "octo_agent_object"
tags : []
seed : 42
wandb_mode : "offline"
results_out_path : "/home/mila/n/nearyc/scratch/projects/vlaps_data/experiments/libero/results"
save_run_video : True
save_run_wrist_video : True
defaults:
  - env_config : libero_object.yaml
  - agent_config : octo_agent.yaml
  - runner_config : libero_object.yaml
agent_config:
  vla_config:
    checkpoint_path : "/home/mila/n/nearyc/scratch/octo/2025-07-11_octo_base_1p5_libero_all_finetune_wrist/octo_finetune/experiment_20250711_174851"
    checkpoint : 100000
    dataset_statistics : "libero_object_no_noops"
hydra:
  run:
    dir: /home/mila/n/nearyc/scratch/projects/vlaps_data/experiments/libero/hydra_outputs/${now:%Y-%m-%d-%H-%M-%S}
wandb:
  wandb_mode: "offline"
  dir: /home/mila/n/nearyc/scratch/projects/vlaps_data/experiments/libero